"""rename to user_language

Revision ID: 940a44eb4792
Revises: a76f6d0bcbea
Create Date: 2024-09-11 16:57:21.507682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940a44eb4792'
down_revision = 'a76f6d0bcbea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_language', sa.String(length=128), nullable=False))
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_column('user_language')

    # ### end Alembic commands ###
