"""testtesttesttest

Revision ID: a76f6d0bcbea
Revises: 8271a924a3d2
Create Date: 2024-09-11 15:49:28.693508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76f6d0bcbea'
down_revision = '8271a924a3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_translates',
    sa.Column('achievement_translate_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('achievement_name', sa.String(length=64), nullable=False),
    sa.Column('achievement_description', sa.Text(), nullable=False),
    sa.Column('achievement_language', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.achievement_id'], ),
    sa.PrimaryKeyConstraint('achievement_translate_id'),
    sa.UniqueConstraint('achievement_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievement_translates')
    # ### end Alembic commands ###
