"""Initial migration.

Revision ID: 0c9878864d49
Revises: 
Create Date: 2024-09-10 21:28:03.529734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9878864d49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievements',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.achievement_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    op.drop_table('user_achievement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievement',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('achievement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.achievement_id'], name='user_achievement_achievement_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_achievement_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id', name='user_achievement_pkey')
    )
    op.drop_table('user_achievements')
    # ### end Alembic commands ###
